service: sls # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  stage: runtime
  region: us-east-2 # Overwrite the default region used. Default is us-east-1
  memorySize: 1024

functions:
  east-west-exploit:
    handler: Lambda-CVE-2014-6271-Exploit.lambda_handler
    role: arn:aws:iam::650143975734:role/lambda_basic_execution
    timeout: 300
    events:
      - http:
          method: get
          path: east-west-exploit
          integration: lambda
          request:
            template:
              application/json: '{ "url" : "$input.params(''url'')", "cmd" : "$input.params(''cmd'')" }'